name: 'Docker build and release'
on:
  push:
    tags:
      - '*'

# cr.brightbox.com/acc-h3nbk/pushtest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: traceroute
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqy mtr-tiny
          mtr -wnr4 cr.brightbox.com >/dev/stderr
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.brightbox.com
          username: cli-wcv2z
          password: b2y7sv1xi4cqpxk
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: |
            cr.brightbox.com/acc-h3nbk/githubtest:${{ steps.tagName.outputs.tag }}
          push: true
