name: 'Docker build and push'
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Install newer containerd
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update -qq
          sudo apt-get install docker-ce docker-ce-cli containerd.io
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.brightbox.com
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_SECRET }}
      - name: Manual docker build and push
        run: |
          docker build -t cr.brightbox.com/acc-h3nbk/githubtest:${{ steps.tagName.outputs.tag }} .
          docker push cr.brightbox.com/acc-h3nbk/githubtest:${{ steps.tagName.outputs.tag }}
      - name: Docker docker buildx build and push
        run: |
          docker --debug=true buildx build --file ./Dockerfile  --tag cr.brightbox.com/acc-h3nbk/githubtest:${{ steps.tagName.outputs.tag }}  --push .
      - name: build-push-action build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: |
            cr.brightbox.com/acc-h3nbk/githubtest:${{ steps.tagName.outputs.tag }}
          push: true
