name: 'Docker build and push'
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.brightbox.com
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_SECRET }}
      - name: build-push-action build only
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: |
            cr.brightbox.com/acc-h3nbk/githubtest:${{ steps.tagName.outputs.tag }}
          push: false
      - name: push
        run: docker push cr.brightbox.com/acc-h3nbk/githubtest:${{ steps.tagName.outputs.tag }}
